//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Que.Management.Sys.UserinfoWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserinfoWebService.UserinfoWebServiceSoap")]
    public interface UserinfoWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Que.Management.Sys.UserinfoWebService.HelloWorldResponse HelloWorld(Que.Management.Sys.UserinfoWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Que.Management.Sys.UserinfoWebService.HelloWorldResponse> HelloWorldAsync(Que.Management.Sys.UserinfoWebService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 user_id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        Que.Management.Sys.UserinfoWebService.LoginResponse Login(Que.Management.Sys.UserinfoWebService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Que.Management.Sys.UserinfoWebService.LoginResponse> LoginAsync(Que.Management.Sys.UserinfoWebService.LoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 user_id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        Que.Management.Sys.UserinfoWebService.RegisterResponse Register(Que.Management.Sys.UserinfoWebService.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<Que.Management.Sys.UserinfoWebService.RegisterResponse> RegisterAsync(Que.Management.Sys.UserinfoWebService.RegisterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Que.Management.Sys.UserinfoWebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Que.Management.Sys.UserinfoWebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Que.Management.Sys.UserinfoWebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Que.Management.Sys.UserinfoWebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Que.Management.Sys.UserinfoWebService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Que.Management.Sys.UserinfoWebService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user_pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ip_addr;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string user_id, string user_pwd, string ip_addr) {
            this.user_id = user_id;
            this.user_pwd = user_pwd;
            this.ip_addr = ip_addr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Que.Management.Sys.UserinfoWebService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Que.Management.Sys.UserinfoWebService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public Que.Management.Sys.UserinfoWebService.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(Que.Management.Sys.UserinfoWebService.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user_pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ip_addr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mac_addr;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string user_id, string user_pwd, string ip_addr, string mac_addr) {
            this.user_id = user_id;
            this.user_pwd = user_pwd;
            this.ip_addr = ip_addr;
            this.mac_addr = mac_addr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public Que.Management.Sys.UserinfoWebService.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(Que.Management.Sys.UserinfoWebService.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(string RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserinfoWebServiceSoapChannel : Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserinfoWebServiceSoapClient : System.ServiceModel.ClientBase<Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap>, Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap {
        
        public UserinfoWebServiceSoapClient() {
        }
        
        public UserinfoWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserinfoWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserinfoWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserinfoWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Que.Management.Sys.UserinfoWebService.HelloWorldResponse Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap.HelloWorld(Que.Management.Sys.UserinfoWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Que.Management.Sys.UserinfoWebService.HelloWorldRequest inValue = new Que.Management.Sys.UserinfoWebService.HelloWorldRequest();
            inValue.Body = new Que.Management.Sys.UserinfoWebService.HelloWorldRequestBody();
            Que.Management.Sys.UserinfoWebService.HelloWorldResponse retVal = ((Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Que.Management.Sys.UserinfoWebService.HelloWorldResponse> Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap.HelloWorldAsync(Que.Management.Sys.UserinfoWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Que.Management.Sys.UserinfoWebService.HelloWorldResponse> HelloWorldAsync() {
            Que.Management.Sys.UserinfoWebService.HelloWorldRequest inValue = new Que.Management.Sys.UserinfoWebService.HelloWorldRequest();
            inValue.Body = new Que.Management.Sys.UserinfoWebService.HelloWorldRequestBody();
            return ((Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Que.Management.Sys.UserinfoWebService.LoginResponse Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap.Login(Que.Management.Sys.UserinfoWebService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string user_id, string user_pwd, string ip_addr) {
            Que.Management.Sys.UserinfoWebService.LoginRequest inValue = new Que.Management.Sys.UserinfoWebService.LoginRequest();
            inValue.Body = new Que.Management.Sys.UserinfoWebService.LoginRequestBody();
            inValue.Body.user_id = user_id;
            inValue.Body.user_pwd = user_pwd;
            inValue.Body.ip_addr = ip_addr;
            Que.Management.Sys.UserinfoWebService.LoginResponse retVal = ((Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Que.Management.Sys.UserinfoWebService.LoginResponse> Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap.LoginAsync(Que.Management.Sys.UserinfoWebService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Que.Management.Sys.UserinfoWebService.LoginResponse> LoginAsync(string user_id, string user_pwd, string ip_addr) {
            Que.Management.Sys.UserinfoWebService.LoginRequest inValue = new Que.Management.Sys.UserinfoWebService.LoginRequest();
            inValue.Body = new Que.Management.Sys.UserinfoWebService.LoginRequestBody();
            inValue.Body.user_id = user_id;
            inValue.Body.user_pwd = user_pwd;
            inValue.Body.ip_addr = ip_addr;
            return ((Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Que.Management.Sys.UserinfoWebService.RegisterResponse Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap.Register(Que.Management.Sys.UserinfoWebService.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public string Register(string user_id, string user_pwd, string ip_addr, string mac_addr) {
            Que.Management.Sys.UserinfoWebService.RegisterRequest inValue = new Que.Management.Sys.UserinfoWebService.RegisterRequest();
            inValue.Body = new Que.Management.Sys.UserinfoWebService.RegisterRequestBody();
            inValue.Body.user_id = user_id;
            inValue.Body.user_pwd = user_pwd;
            inValue.Body.ip_addr = ip_addr;
            inValue.Body.mac_addr = mac_addr;
            Que.Management.Sys.UserinfoWebService.RegisterResponse retVal = ((Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Que.Management.Sys.UserinfoWebService.RegisterResponse> Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap.RegisterAsync(Que.Management.Sys.UserinfoWebService.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<Que.Management.Sys.UserinfoWebService.RegisterResponse> RegisterAsync(string user_id, string user_pwd, string ip_addr, string mac_addr) {
            Que.Management.Sys.UserinfoWebService.RegisterRequest inValue = new Que.Management.Sys.UserinfoWebService.RegisterRequest();
            inValue.Body = new Que.Management.Sys.UserinfoWebService.RegisterRequestBody();
            inValue.Body.user_id = user_id;
            inValue.Body.user_pwd = user_pwd;
            inValue.Body.ip_addr = ip_addr;
            inValue.Body.mac_addr = mac_addr;
            return ((Que.Management.Sys.UserinfoWebService.UserinfoWebServiceSoap)(this)).RegisterAsync(inValue);
        }
    }
}
